name: Compile and upload ESP32 Arduino Sketch

on:
  push:
    branches:
      - main

env:
  PLATFORMIO_CI_SRC: src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Install required libraries
      run: |
        git clone https://github.com/schreibfaul1/ESP32-TFT-Library-ILI9486.git lib/ESP32-TFT-Library-ILI9486
        git clone https://github.com/schreibfaul1/ESP32-audioI2S.git lib/ESP32-audioI2S
        git clone https://github.com/schreibfaul1/ESP32-IR-Remote-Control.git lib/ESP32-IR-Remote-Control

    - name: Compile code
      run: pio run --environment esp32

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware.bin
        path: .pio/build/esp32/firmware.bin
