name: Build with PlatformIO for ESP32

on:
  push:
    branches:
      - main

env:
  PLATFORMIO_CI_SRC: src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Compile code
      run: |
           export GIT_IDENT=$(git rev-parse --short HEAD)
           platformio project init
           pio run
           # pio run -v -t upload || true # Show all firmware parts and commands
           mkdir -p firmware/esp32 firmware/esp32cam firmware/esp32s2 # firmware/esp32s3 firmware/esp32c3
           cp .pio/build/esp32/firmware.bin firmware/esp32
           cp ${{ github.workspace }}/.pio/build/esp32/bootloader.bin firmware/esp32
           cp ${{ github.workspace }}/.pio/build/esp32/partitions.bin firmware/esp32
           cp ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin firmware/esp32
           cp .pio/build/esp32cam/firmware.bin firmware/esp32cam
           cp ${{ github.workspace }}/.pio/build/esp32cam/bootloader.bin firmware/esp32cam
           cp ${{ github.workspace }}/.pio/build/esp32cam/partitions.bin firmware/esp32cam
           cp ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin firmware/esp32cam
           cp .pio/build/esp32s2/firmware.bin firmware/esp32s2
           cp ${{ github.workspace }}/.pio/build/esp32s2/bootloader.bin firmware/esp32s2
           cp ${{ github.workspace }}/.pio/build/esp32s2/partitions.bin firmware/esp32s2
           cp ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin firmware/esp32s2
           #cp .pio/build/esp32s3/firmware.bin firmware/esp32s3
           #cp ${{ github.workspace }}/.pio/build/esp32s3/bootloader.bin firmware/esp32s3
           #cp ${{ github.workspace }}/.pio/build/esp32s3/partitions.bin firmware/esp32s3
           #cp ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin firmware/esp32s3
           #cp .pio/build/esp32c3/firmware.bin firmware/esp32c3
           #cp ${{ github.workspace }}/.pio/build/esp32c3/bootloader.bin firmware/esp32c3
           #cp ${{ github.workspace }}/.pio/build/esp32c3/partitions.bin firmware/esp32c3
           #cp ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin firmware/esp32c3

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: firmware/
