name: Build with PlatformIO for ESP32

on:
  push:
    branches:
      - main

env:
  PLATFORMIO_CI_SRC: src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Compile code
      run: |
           platformio project init
           pio run --environment esp32
           pio run -v -t upload || true # Show all firmware parts and commands
           mkdir -p firmware
           cp .pio/build/esp32/firmware.bin firmware/
           cp ~/work/esp32-i2s-webradio/esp32-i2s-webradio/.pio/build/esp32/bootloader.bin firmware/
           cp ~/work/esp32-i2s-webradio/esp32-i2s-webradio/.pio/build/esp32/partitions.bin firmware/
           cp ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin firmware/


    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: firmware/
